### ISSUE TITLE
Undefined functions/variables

### ISSUE THREAD

**Issue by Nucs** [kayuksel/pytorch-ars#1]
The imports are messed up but most of them are obvious.
The following, I cannot find/figure: `Arch3`, `tq(...)`, `No_Channels`, `Input_Size`

Hence the issue lies with the following code:
``` python
execfile('start.py')
execfile('archs.py')
```

**Comment by kayuksel** [comment]
@Nucs Hello, I haven't put the architecture because I was working with a private one. Basically, you can apply the code to any architecture you want. tq is just for a console progress bar and you can install tqdm==4.30.0

**Comment by kayuksel** [comment]
@Nucs You can also directly run ars_dataparallel.py; that script doesn't have any external imports, etc.
